mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

quiz/urls.py
from django.urls import path
from .views import IndexView, AddView, DeleteView, QuizView, EditView

app_name = 'quiz'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:quiz_id>/', QuizView.as_view(), name='questionnaire'),
    path('<pk>/edit/', EditView.as_view(), name='edit',),
    path('<pk>/delete/', DeleteView.as_view(), name='delete'),
    path('create/', AddView.as_view(), name='create'),
]

quiz/models.py
from django.db import models
from django.utils import timezone

One_to_Four = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
]


class Quiz(models.Model):
    title = models.CharField(max_length=40)
    author = models.CharField(max_length=40)
    dt_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.title

    def quizquestion(self):
        return self.quizquestion_set.all()

    class Meta:
        verbose_name = 'Quizze'


class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(blank=True,max_length=100)
    correct = models.IntegerField(choices=One_to_Four)
    option1 = models.CharField(blank=True,max_length=50)
    option2 = models.CharField(max_length=50)
    option3 = models.CharField(max_length=50)
    option4 = models.CharField(max_length=50)

    def __str__(self):
        return self.question_text

quiz/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import ModelForm, inlineformset_factory
from quiz.models import Quiz, QuizQuestion


class QuestionForm(ModelForm):
    question_text = forms.CharField(required=True, initial="Question")

    class Meta:
        model = QuizQuestion
        exclude = ('quiz',)

EditFormSet = inlineformset_factory(Quiz, QuizQuestion, form=QuestionForm, extra=1)
CreateFormSet = inlineformset_factory(Quiz, QuizQuestion, form=QuestionForm, extra=3)


class VotingForm(forms.Form):
    def __init__(self, *args, **kwargs):
        quiz = kwargs.pop('quiz')
        super(VotingForm, self).__init__(*args, **kwargs)

        i = 0
        for question in quiz:
            self.helper = FormHelper()
            self.helper.form_id = 'form_question'
            self.helper.form_class = 'blueForms'
            self.helper.add_input(Submit('submit', 'Submit',
                                         css_id="submitBtn",
                                         css_class='btn btn-primary btn-lg btn-block'))
            self.fields['question_text' + str(i)] = forms.ChoiceField(
                widget=forms.RadioSelect, label=question, choices=[
                    (1, quiz[i].option1),
                    (2, quiz[i].option2),
                    (3, quiz[i].option3),
                    (4, quiz[i].option4), ])
            i = i + 1

quiz/views.py
from django.db import transaction
from django.shortcuts import get_object_or_404, render
from django.template.response import TemplateResponse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, FormView, UpdateView
from .forms import VotingForm, CreateFormSet, EditFormSet
from .models import Quiz, QuizQuestion


class IndexView(ListView):
    template_name = "quiz/index.html"
    queryset = Quiz.objects.all()


class QuizView(FormView, DetailView):
    template_name = 'quiz/questionnaire.html'
    form_class = VotingForm
    queryset = QuizQuestion.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = QuizQuestion.objects.filter(quiz=self.kwargs["quiz_id"]).values()
        context['question'] = list(question)
        return context

    def get_form_kwargs(self):
        kwargs = super(QuizView, self).get_form_kwargs()
        quiz_id = QuizQuestion.objects.filter(quiz=self.kwargs["quiz_id"])
        kwargs['quiz'] = quiz_id
        return kwargs

    def get_object(self):
        quiz_id = self.kwargs.get("quiz_id")
        return get_object_or_404(Quiz, id=quiz_id)

# Does take you to the newly created page once completed
class AddView(CreateView):
    model = Quiz
    fields = '__all__'
    success_url = '../'
    template_name = 'quiz/create.html'

    def get_context_data(self, **kwargs):
        data = super(AddView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['quizquestion'] = CreateFormSet(self.request.POST, self.request.FILES)
        else:
            data['quizquestion'] = CreateFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        quizquestion = context['quizquestion']
        with transaction.atomic():
            self.object = form.save()

            if quizquestion.is_valid():
                quizquestion.instance = self.object
                quizquestion.save()
                print("question valid")
            else:
                print("question invalid")

        return super(AddView, self).form_valid(form)

    def form_invalid(self, form):
        print("invalid form")

class DeleteView(DeleteView):
    model = Quiz
    template_name = 'quiz/delete.html'
    success_url = '../../'


class EditView(UpdateView):
    model = Quiz
    fields = '__all__'
    template_name = 'quiz/edit.html'
    success_url = '../'

    def get_context_data(self, **kwargs):
        data = super(EditView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['quizquestion'] = EditFormSet(self.request.POST, instance=self.object)
        else:
            data['quizquestion'] = EditFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        quizquestion = context['quizquestion']

        with transaction.atomic():
            self.object = form.save()

            if quizquestion.is_valid():
                quizquestion.instance = self.object
                quizquestion.save()
        return super(EditView, self).form_valid(form)

quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>

        <div class="mx-auto" style="width: 500px;">
            <br>
            <h1>Sebs Django Questionnaire</h1>
            <br>
            <title>Django Website</title>
        </div>
    </head>
    <body>
    <div class="mx-auto" style="width:500px">

        {% block content %}
        {% endblock %}

    </div>
</body>
</html>

quiz/templates/quiz/create.html
{% extends 'quiz/base.html' %}

{%  load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}

        {{ quizquestion.management_form }}

        {% for question in quizquestion %}
            <div id="question">
                <br>
                {{ question|crispy }}
            </div>
        {%  endfor %}
        <button id='new_question' class="btn btn-info btn-sm btn-block" type="button"/>Add Question</button>
        <br/>
        <input id='submitBtn' class="btn btn-primary btn-md" type="submit" value="Create"/>
        <a class="btn btn-link" href="{% url 'quiz:index' %}">Back to the list</a>
    </form>
    <br>
<script>
    $(document).ready(function() {
        var questionList = $( "div[id='question']" );
        console.log(questionList);
        for(let i = 1; i < questionList.length; i++){

            $(questionList[i]).hide();
        }
        let loop = 1;

        $("#new_question").click(function() {
            {#$(questionList[loop-1]).slideUp();#}
            $(questionList[loop]).slideDown();
            loop++;
            if(loop>=questionList.length)
                $("#new_question").prop('disabled',true);
        });
    });
</script>
{% endblock %}

quiz/templates/quiz/delete.html
{% extends 'quiz/base.html' %}

{% block content %}

    <div class="mx-auto" style="width: 600px;">
        <form action="." method="POST">
            {% csrf_token %}
            <h3>Are you sure you want to delete the quiz "{{ object.title }}"?</h3>
            <input type="submit" value="Yes" class="btn btn-outline-danger btn-sm" />
            <a href="../" class="btn btn-outline-primary btn-sm">Cancel</a>
        </form>
    </div>

{% endblock %}

quiz/templates/quiz/detail.html
{% extends 'quiz/base.html' %}

    {% block title %}
        <h2> {{ object.name }} </h2>
    {% endblock %}

{% block content %}


    <a href="{% url 'quiz:edit' object.id %}"> edit </a>
    <a href="{% url 'quiz:delete' object.id %}"> delete </a>

    <form action="{% url 'quiz:vote' object.id %}" method="post">

        {% include "quiz/voteTemplate.html" with question_text=object.q1_question answer_text=object.q1_answer radioName="group1" %}
        {% include "quiz/voteTemplate.html" with question_text=object.q2_question answer_text=object.q2_answer radioName="group2" %}
        {% include "quiz/voteTemplate.html" with question_text=object.q3_question answer_text=object.q3_answer radioName="group3" %}
        {% include "quiz/voteTemplate.html" with question_text=object.q4_question answer_text=object.q4_answer radioName="group4" %}
        {% include "quiz/voteTemplate.html" with question_text=object.q5_question answer_text=object.q5_answer radioName="group5" %}

        <br><input type="submit" value="Done">
    </form>

{% endblock %}

quiz/templates/quiz/edit.html
{% extends 'quiz/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy}}
        <br>

        {{ quizquestion.management_form }}

        {% for form in quizquestion.forms %}
            {{ form|crispy }}
            <br/>
        {%  endfor %}

        <input class="btn btn-primary btn-md" type="submit" value="Save"/>
        <a class="btn btn-link" href="{% url 'quiz:index' %}">Back to the list</a>
    </form>
    <br>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block content %}
    <div class="mx-auto" style="">
        {% if object_list %}
            <ul>
            {% for quiz in object_list %}
                <li><a href="{% url 'quiz:questionnaire' quiz.id %}">{{ quiz.title }}</a> --
                <a href="{% url 'quiz:edit' quiz.id %}"> edit </a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
        <a class="create_quiz" href="{% url 'quiz:create' %}">Add new quiz</a>
    </div>
{% endblock %}

quiz/templates/quiz/questionnaire.html
{% extends 'quiz/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="mx-auto" style="width: 600px;">
        <h2> {{ object.title }} Quiz </h2>
        <h6> {{ object.dt_date }}</h6>
        <h6> By: {{ object.author }}</h6>
        <a href="{% url 'quiz:edit' object.id %}" class="btn btn-outline-secondary btn-sm" role="button" aria-pressed="true">Edit </a>
        <a href="{% url 'quiz:delete' object.pk %}" class="btn btn-outline-danger btn-sm">Delete </a>

        {{ question|json_script:"quiz-question" }}
        <br><br/>
        {% crispy form %}
        <br><br/>
    </div>

<script>
    $(document).ready(function() {
        $("#form_question").submit(function(e) {
            e.preventDefault();
        });

        //Gets question object
        const question = JSON.parse(document.getElementById('quiz-question').textContent);
        //Gets a list of all the questions by id
        var questionList = $( "div[id='form_question']" );
        var hasGuessed = true;
        var score = 0;
        var loop = 0;

        // Hides all apart from the first question
        for(let i = 1; i < questionList.length; i++){
            $(questionList[i]).hide();
        }

        $("#submitBtn").prop('disabled', true);

        // When option is selected able to submit
        $("[type='radio']").on('change',function(){
            $("#submitBtn").prop('disabled', false);});

        $("#submitBtn").click(function(){
            //If retry button called clear data and show first question
            if(loop>=questionList.length){
                $(".score").remove();
                $("#submitBtn").removeClass('btn-success').removeClass('btn-danger').addClass('btn-primary').prop('value','Submit');
                $('.custom-control-label').css('color','black');
                $("#submitBtn").prop('disabled', true);
                loop = 0;
                score = 0;
                $(questionList[loop]).slideToggle("slow");
            } else {
                // If the user has chosen an option
                if (hasGuessed) {
                    let selected_value = $("[type='radio']:checked").val();
                    let label_text = $('label[for="' + "id_question_text" + loop + "_" + selected_value + '"]');
                    let correct_answer = question[loop].correct;

                    // If option was correct increase score
                    if (selected_value == correct_answer) {
                        label_text.css('color', 'green');
                        $("#submitBtn").removeClass('btn-primary').addClass('btn-success').prop('value', 'Correct');
                        score++;
                    } else {
                        // If option was incorrect highlight wrong and right answers
                        label_text.effect("shake", {times: 2}, 300).css('color', 'red');
                        $('label[for="' + "id_question_text" + loop + "_" + correct_answer + '"]').css('color', 'green');
                        $("#submitBtn").removeClass('btn-primary').addClass('btn-danger').prop('value', 'Wrong');
                    }
                    hasGuessed = false;
                } else {
                    // Next click of the button will hide the previous question and display the next
                    $('input[type="radio"]').prop('checked', false);
                    $("#submitBtn").removeClass('btn-success').removeClass('btn-danger').addClass('btn-primary').prop('value', 'Submit');
                    $(questionList[loop]).slideToggle("slow");
                    $(questionList[loop + 1]).slideToggle("slow");
                    $("#submitBtn").prop('disabled', true);
                    loop++;
                    hasGuessed = true;

                    // If last question display score and give option to restart
                    if (loop >= questionList.length) {
                        $("#submitBtn").after("<br> <p class='score'>You scored " + score + " out of " + questionList.length + " </p>").slideDown();
                        $("#submitBtn").prop('value','Retry');
                        console.log(questionList.length);
                        $("#submitBtn").prop('disabled', false);
                    }
                }
            }
        });
    });
</script>
{% endblock %}

quiz/templates/quiz/votingError.html
{% extends 'quiz/base.html' %}

{% block content %}

    <div class="mx-auto" style="width: 600px;">
        <p> Please answer all questions to get your results </p>
    </div>
{% endblock %}